011
Signed-off-by: DiasPedroQA <diaspedro.dev@gmail.com>

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -69,14 +69,23 @@ jobs:
 
       - name: Ensure virtual environment and dependencies
         run: |
+          echo "recreating virtual environment"
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install -r requirements.txt
+
+      # Verificar se o ambiente virtual foi criado corretamente
+      - name: Check virtual environment
+        run: |
           if [ ! -d ".venv" ]; then
-            echo "recreating virtual environment"
-            python -m venv .venv
-            source .venv/bin/activate
-            pip install -r requirements.txt
-          else
-            echo "venv found, activating"
-            source .venv/bin/activate
+            echo "Virtual environment not found. Please run the setup job first."
+            exit 1
+          fi
+          echo "Virtual environment found."
+          # Verificar se o ambiente virtual está ativo
+          if [ -z "$VIRTUAL_ENV" ]; then
+            echo "Virtual environment not activated. Please activate the virtual environment."
+            exit 1
           fi
 
       # Rodar o flake8 para garantir a qualidade do código
